version: "3"
services:
    mysql:
        container_name: laraplay-mysql
        image: boudewijn00/mysql:latest
        volumes:
            - laraplay-mysql:/var/lib/mysql
        environment:
            MARIADB_DATABASE: laraplay-db
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: laraplay-user
            MARIADB_PASSWORD: laraplay-password
        ports:
            - 13306:3306
    redis:
        container_name: laraplay-redis
        image: redis:latest
        ports:
            - 16379:6379
        volumes:
            - laraplay-redis:/data
volumes:
    laraplay-mysql:
        driver: "local"
    laraplay-redis:
        driver: "local"
